"""Códigos estáveis das funções técnicas universais."""

ROMANA_FUNCTION_CODES = (
    "TECIDO_ROMANA", "VARETA_ROMANA", "TAMPA_VARETA_ROMANA",
    "CABECEIRA_ROMANA", "EIXO_ROMANA", "BASE_ROMANA", "TAMPA_BASE_ROMANA",
    "CAVALETE_CARRETEL_ROMANA", "GUIA_CORDA_ROMANA", "CORDA_ROMANA_1MM",
    "ESPAGUETE_ROMANA_2_5MM", "ESPAGUETE_BASE_ROMANA_3MM",
    "COMANDO_NORMAL_ROMANA", "COMANDO_REDUCAO_ROMANA",
    "CORRENTE_SEM_FIM_ROMANA_BOLA10", "CORRENTE_JUTA_BOLA10_PERSONALIZADA",
    "PENDULO_CORRENTE_ROMANA",
)

ROLO_FUNCTION_CODES = (
    "TECIDO_ROLO", "TUBO_ROLO_32MM", "TUBO_ROLO_38MM", "TUBO_ROLO_43MM",
    "TUBO_ROLO_65MM", "TUBO_ROLO_70MM", "FITA_TUBO_ROLO",
    "BASE_ROLO", "FITA_BASE_ROLO", "ESPAGUETE_BASE_ROLO", "CORRENTE_ROLO",
    "EMENDA_CORRENTE_ROLO", "TAMPA_BASE_ROLO", "COMANDO_ROLO_32MM",
    "COMANDO_ROLO_38MM", "COMANDO_ROLO_43MM",
)
